### ISSUE TITLE
Optimize `Conf` messages in `BinaryAgreement`

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/hbbft#229] opened 2018-09-12 09:12 UTC
Consider possible optimizations of `Conf` messages that increase the likelihood of termination in a `BinaryAgreement` epoch. See https://github.com/amiller/HoneyBadgerBFT/issues/59#issuecomment-408664323, #37 and #44.

**Comment by afck** [comment] 2018-10-31 14:12
I think this is a duplicate of #198.

**Closed by afck** 2018-10-31 14:12 UTC
Labels: Priority: Low, optimization
